name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - rafaelurben
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What actually happened?
      description: What did you see?
      placeholder: Tell me what you see!
    validations:
      required: true
  - type: textarea
    id: what-should-have-happened
    attributes:
      label: What should have happened?
      description: What did you expect to happen?
      placeholder: Tell me what you wanted to see!
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce?
      description: Steps to reproduce the behaviour. If not applicable, the things you did before/when the bug occured.
      placeholder: Tell me how I can see it too!
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: If applicable, what environment did you experience the bug in?
      value: |
          - **Operating System**: Windows/macOS/Linux
          - **Browser**: Firefox/Edge/Chrome
          - ...
      render: markdown
  - type: input
    id: version
    attributes:
      label: Version
      description: If applicable, what version of the software did you experience the bug in?
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: |
        Links? References? Screenshots? Anything that will give me more context about the issue you are encountering!
  
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist 
      options:
        - label: I have filled out all applicable fields to the best of my knowledge.
          required: true
        - label: I can be contacted via answer to this issue or have provided alternative contact information under "Additional Information".
          required: true
