name: Generate README cards

on:
  schedule:
    - cron: "5 4 * * *"
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Generate stats card (dark)
        uses: readme-tools/github-readme-stats-action@8614f3a61601854731381d853f8566867754a5ca # v2.0.0
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&card_width=495&theme=dark&rank_icon=percentile&count_private=true
          path: cards/stats-dark.svg
          token: ${{ secrets.GH_STAT_TOKEN }}

      - name: Generate stats card (light)
        uses: readme-tools/github-readme-stats-action@8614f3a61601854731381d853f8566867754a5ca # v2.0.0
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&card_width=495&theme=default&rank_icon=percentile&count_private=true
          path: cards/stats-light.svg
          token: ${{ secrets.GH_STAT_TOKEN }}

      - name: Generate top languages card (dark)
        uses: readme-tools/github-readme-stats-action@8614f3a61601854731381d853f8566867754a5ca # v2.0.0
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=12&card_width=495&theme=dark
          path: cards/top-langs-dark.svg
          token: ${{ secrets.GH_STAT_TOKEN }}

      - name: Generate top languages card (light)
        uses: readme-tools/github-readme-stats-action@8614f3a61601854731381d853f8566867754a5ca # v2.0.0
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=12&card_width=495&theme=default
          path: cards/top-langs-light.svg
          token: ${{ secrets.GH_STAT_TOKEN }}

      - name: Generate wakatime card (dark)
        uses: readme-tools/github-readme-stats-action@8614f3a61601854731381d853f8566867754a5ca # v2.0.0
        with:
          card: wakatime
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=12&theme=dark
          path: cards/wakatime-dark.svg
          token: ${{ secrets.GH_STAT_TOKEN }}

      - name: Generate wakatime card (light)
        uses: readme-tools/github-readme-stats-action@8614f3a61601854731381d853f8566867754a5ca # v2.0.0
        with:
          card: wakatime
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=12&theme=default
          path: cards/wakatime-light.svg
          token: ${{ secrets.GH_STAT_TOKEN }}

      - name: Commit cards
        run: |
          git checkout -b output
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add cards/*.svg
          git commit -m "chore: Generate README cards"
          git push --set-upstream origin output --force
